pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://corwatts.com
exclude: [rakefile]

first_name: Corey
last_name: Watts
banner_text: hi. i'm corey.
github: https://github.com/CorWatts
